# Generated by Django 5.0.2 on 2024-02-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('date_sent', models.DateField()),
                ('date_received', models.DateField()),
                ('addressed_to', models.CharField(max_length=100)),
                ('signatory', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='incoming_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prioritization', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default=[], max_length=20)),
                ('classification', models.CharField(choices=[('Unclassified', 'Unclassified'), ('Confidential', 'Confidential'), ('Secret', 'Secret'), ('Top Secret', 'Top Secret')], default=[], max_length=20)),
                ('folder', models.CharField(choices=[('Group A', 'Group A'), ('Group B', 'Group B'), ('Group C', 'Group C')], default=[], max_length=20)),
            ],
        ),
    ]
