# Generated by Django 5.0.2 on 2024-02-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingfiles',
            options={'ordering': ['-created_at', '-folder', 'subject']},
        ),
    ]
